# Cloud Build Configuration - Website Assistant v3.0
# Builds and deploys both backend and frontend to Cloud Run

steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/website-assistant-backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', 'backend']
    id: 'build-backend'

  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/website-assistant-frontend:$COMMIT_SHA',
      '-f', 'frontend/Dockerfile',
      '--build-arg', 'NEXT_PUBLIC_API_URL=https://api.barriosa2i.com',
      '--build-arg', 'NEXT_PUBLIC_WS_URL=wss://api.barriosa2i.com',
      'frontend'
    ]
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/website-assistant-backend:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/website-assistant-frontend:$COMMIT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'website-assistant-backend'
      - '--image=gcr.io/$PROJECT_ID/website-assistant-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--timeout=300'
      - '--set-env-vars=ENV=production'
      - '--set-secrets=ANTHROPIC_API_KEY=anthropic-api-key:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest,DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest,RABBITMQ_URL=rabbitmq-url:latest'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'website-assistant-frontend'
      - '--image=gcr.io/$PROJECT_ID/website-assistant-frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=5'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

images:
  - 'gcr.io/$PROJECT_ID/website-assistant-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/website-assistant-frontend:$COMMIT_SHA'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
